### ISSUE TITLE
[bug] error on table_metadata

### ISSUE THREAD

**Issue by kihyuk-nam** [kihyuk-nam/traindb-model#4]
nam@dev1:~/Projects/traindb-model$ ./tests/test_rspn_infer.sh 
SELECT COUNT(*) FROM order_products
Traceback (most recent call last):
  File "/home/nam/Projects/traindb-model/tools/TrainDBCliModelRunner.py", line 104, in <module>
    main()
  File "/home/nam/Projects/traindb-model/tools/TrainDBCliModelRunner.py", line 87, in main
    aqp_result, confidence_interval = runner.infer(args.modeltype_class, args.modeltype_uri, args.model_path, args.agg_expr, args.group_by_column, args.where_condition)
  File "/home/nam/Projects/traindb-model/tools/TrainDBCliModelRunner.py", line 30, in infer
    infer_results = super()._infer(modeltype_class, modeltype_path, model_path, agg_expr, group_by_column, where_condition)
  File "/home/nam/Projects/traindb-model/tools/TrainDBBaseModelRunner.py", line 45, in _infer
    model.load(model_path)
  File "/home/nam/Projects/traindb-model/models/RSPN.py", line 135, in load
    self.spn_ensemble = read_ensemble(os.path.join(input_path, 'spn_ensembles'), True)
  File "/home/nam/Projects/traindb-model/models/rspn/ensemble_compilation/spn_ensemble.py", line 226, in read_ensemble
    _build_reverse_spn_dict(spn)
  File "/home/nam/Projects/traindb-model/models/rspn/ensemble_compilation/spn_ensemble.py", line 299, in _build_reverse_spn_dict
    spn.table_meta_data[table]['fd_dict'] = dict()
TypeError: list indices must be integers or slices, not str

**Comment by kihyuk-nam** [comment]
suspicious of  [this line](https://github.com/kihyuk-nam/traindb-model/blob/1cbfa13a47672b6c017273aeef5a38fb5c7ff3cc/models/RSPN.py#L332)

table_data —> real_data

**Comment by kihyuk-nam** [comment]
575c3efd1a1168ebee998a5b6865cc07c85331ea
commented out some erroneous lines (424-440) in RSPN.py
